---
abstract: 'Console logging in your browser'
author:
  - 'Glen Hinkle <tempire@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ConsoleLogger
requires:
  Mojolicious: 1.02
resources:
  repository: git://github.com/tempire/mojolicious-plugin-consolelogger.git
version: 0.02
